openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  # ...
servers:
  - url: http://localhost:3000
  - url: https://hw7-swagger-p9tq.onrender.com

paths:
  # BU KISIM ÇOK ÖNEMLİ!
  # Eğer burası boşsa Swagger da boş görünür.
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{contactId}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml

  /users/register:
    post:
      $ref: ../swagger/paths/users/register.yaml
  
  /users/login:
    post:
      $ref: ../swagger/paths/users/login.yaml

components:
  # ... components kodlarınız ...