openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  description: GoIT Node.js Ödevi
servers:
  - url: https://hw7-swagger-p9tq.onrender.com/api
    description: Render Live Server
tags:
  - name: Contacts
  - name: Auth
paths:
  /users/register:
    post:
      tags: [Auth]
      summary: Kayıt Ol
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '201':
          description: Başarılı
  /users/login:
    post:
      tags: [Auth]
      summary: Giriş Yap
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: Başarılı
  /contacts:
    get:
      tags: [Contacts]
      summary: Listele
      responses:
        '200':
          description: Liste
    post:
      tags: [Contacts]
      summary: Ekle
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
      responses:
        '201':
          description: Oluşturuldu
  /contacts/{contactId}:
    get:
      tags: [Contacts]
      summary: Detay Getir
      parameters:
        - name: contactId
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Detay
    delete:
      tags: [Contacts]
      summary: Sil
      parameters:
        - name: contactId
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Silindi
    patch:
      tags: [Contacts]
      summary: Güncelle
      parameters:
        - name: contactId
          in: path
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Güncellendi
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT